export const adminKeys = {
  bootstrap: (slug: string) => [slug, 'bootstrap'] as const,
  days: (slug: string) => [slug, 'days'] as const,
  dayTimeline: (slug: string, date: string) => [slug, 'days', date, 'timeline'] as const,
  dayExpenses: (slug: string, dayId: string) => [slug, 'days', dayId, 'expenses'] as const,
  dayGifts: (slug: string, dayId: string) => [slug, 'days', dayId, 'gifts'] as const,
  timeline: (slug: string) => [slug, 'timeline'] as const,
  activeTimeline: (slug: string) => [slug, 'timeline', 'active'] as const,
  tasks: (slug: string) => [slug, 'tasks'] as const,
  archivedTasks: (slug: string) => [slug, 'archived-tasks'] as const,
  members: (slug: string) => [slug, 'members'] as const,
  accessGroups: (slug: string) => [slug, 'access-groups'] as const,
  availableResources: () => ['available-resources'] as const,
  invitation: (slug: string) => [slug, 'invitation'] as const,
  guests: (slug: string) => [slug, 'guests'] as const,
  budget: (slug: string) => [slug, 'budget'] as const,
  gifts: (slug: string) => [slug, 'gifts'] as const,
  pages: (slug: string) => [slug, 'pages'] as const,
  templates: (slug: string) => [slug, 'templates'] as const,
  themes: (slug: string) => [slug, 'themes'] as const,
  settingsEvent: (slug: string) => [slug, 'settings', 'event'] as const,
  settingsAppearance: (slug: string) => [slug, 'settings', 'appearance'] as const,
  settingsNotifications: (slug: string, memberId: string) =>
    [slug, 'settings', 'notifications', memberId] as const,
}